//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_KİTAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_KİTAP()
        {
            this.TBL_HAREKET = new HashSet<TBL_HAREKET>();
        }
    
        public int ID { get; set; }
        public string KitapAd { get; set; }
        public string KitapBasimYili { get; set; }
        public string KitapYayınEvi { get; set; }
        public string KitapSayfaSayısı { get; set; }
        public Nullable<byte> Kategori { get; set; }
        public Nullable<int> KitapYazar { get; set; }
        public Nullable<bool> KitapDurum { get; set; }
        public string KitapResim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_HAREKET> TBL_HAREKET { get; set; }
        public virtual TBL_KATEGORİ TBL_KATEGORİ { get; set; }
        public virtual TBL_YAZAR TBL_YAZAR { get; set; }
    }
}
