//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UYELER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_UYELER()
        {
            this.TBL_CEZALAR = new HashSet<TBL_CEZALAR>();
            this.TBL_HAREKET = new HashSet<TBL_HAREKET>();
        }
    
        public int ID { get; set; }
        public string UyeAdSoyad { get; set; }
        public string UyeMail { get; set; }
        public string UyeKullaniciAd { get; set; }
        public string UyeSifre { get; set; }
        public string UyeFotograf { get; set; }
        public string UyeTelefon { get; set; }
        public string UyeOkul { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CEZALAR> TBL_CEZALAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_HAREKET> TBL_HAREKET { get; set; }
    }
}
